# -*- coding: utf-8 -*-
"""Scrapper con cookie.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1quP6_K6L8hFElmwUt46Kb8VA1Dt_5NB-
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
from tqdm import tqdm
import os

COOKIE = os.getenv("SBBL_COOKIE")
print("Cookie cargada:", COOKIE is not None)
HEADERS = {
    "User-Agent": "Mozilla/5.0",
    "Cookie": COOKIE
}

START_TEAM = 1
END_TEAM = 350
DELAY = 0.1

session = requests.Session()
session.headers.update(HEADERS)

data = []

for team_id in tqdm(range(START_TEAM, END_TEAM)):

    url = f"https://sbbl.es/equipos/{team_id}"
    response = session.get(url)

    if response.status_code != 200:
        continue

    soup = BeautifulSoup(response.text, "html.parser")

    team_name_tag = soup.select_one("h1")
    team_name = team_name_tag.text.strip() if team_name_tag else f"team_{team_id}"

    players = soup.select(".agent-name")

    for p in players:
        data.append({
            "team_id": team_id,
            "team": team_name,
            "player": p.text.strip()
        })

    time.sleep(DELAY)

df = pd.DataFrame(data)

df

df.to_csv("sbbl_players.csv", index=False)

def detectar_equipos(lista_jugadores, df, min_jugadores=3):

    jugadores = [j.lower() for j in lista_jugadores]

    df_temp = df.copy()
    df_temp["player_lower"] = df_temp["player"].str.lower()

    coincidencias = df_temp[df_temp["player_lower"].isin(jugadores)]

    resultado = (
        coincidencias
        .groupby("team")
        .agg(
            jugadores_encontrados=("player", list),
            total=("player", "count")
        )
        .reset_index()
    )

    resultado = resultado[resultado["total"] >= min_jugadores]

    return resultado.sort_values("total", ascending=False)