# -*- coding: utf-8 -*-
"""scraper

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C76MEiEFq2t7vk_L-3g2PJdc9gi78fYg
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
from tqdm import tqdm
from datetime import datetime

START_TEAM = 1
END_TEAM = 200
DELAY = 0.1

session = requests.Session()

headers = {
    "User-Agent": "Mozilla/5.0",
    "Accept-Language": "es-ES,es;q=0.9",
}

session.headers.update(headers)

# visitar la página principal primero
session.get("https://sbbl.es")

data = []

for team_id in tqdm(range(START_TEAM, END_TEAM)):

    url = f"https://sbbl.es/equipos/{team_id}"
    response = session.get(url)

    if response.status_code != 200:
        continue

    soup = BeautifulSoup(response.text, "html.parser")

    team_name_tag = soup.select_one("h1")
    team_name = team_name_tag.text.strip() if team_name_tag else f"team_{team_id}"

    players = soup.select(".agent-name")

    for p in players:
        data.append({
            "team_id": team_id,
            "team": team_name,
            "player": p.text.strip()
        })

    time.sleep(DELAY)

df.to_csv("sbbl_players.csv", index=False)
print("Dataset guardado")

def detectar_equipos(lista_jugadores, df, min_jugadores=3):

    jugadores = [j.lower() for j in lista_jugadores]

    df_temp = df.copy()
    df_temp["player_lower"] = df_temp["player"].str.lower()

    coincidencias = df_temp[df_temp["player_lower"].isin(jugadores)]

    resultado = (
        coincidencias
        .groupby("team")
        .agg(
            jugadores_encontrados=("player", list),
            total=("player", "count")
        )
        .reset_index()
    )

    resultado = resultado[resultado["total"] >= min_jugadores]

    return resultado.sort_values("total", ascending=False)

from datetime import datetime

with open("last_update.txt", "w") as f:
    f.write(datetime.now().strftime("%d %b %Y %H:%M"))