# -*- coding: utf-8 -*-
"""scrapper

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C76MEiEFq2t7vk_L-3g2PJdc9gi78fYg
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
from tqdm import tqdm
from datetime import datetime

START_TEAM = 1
END_TEAM = 200
DELAY = 0.1

session = requests.Session()

session.headers.update({
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Language": "es-ES,es;q=0.9,en;q=0.8",
    "Connection": "keep-alive",
    "Upgrade-Insecure-Requests": "1"
})

# visitar la página principal primero
session.get("https://sbbl.es")

data = []

for team_id in tqdm(range(START_TEAM, END_TEAM + 1)):

    url = f"https://sbbl.es/equipos/{team_id}"
    response = session.get(url)

    # DEBUG SOLO PARA UN EQUIPO
    if team_id == 53:
        print("DEBUG HTML:")
        print(response.text[:1000])

    if response.status_code != 200:
        continue

    soup = BeautifulSoup(response.text, "html.parser")

    team_name_tag = soup.select_one("h1")
    team_name = team_name_tag.text.strip() if team_name_tag else f"team_{team_id}"

    players = soup.select(".agent-name")

    for p in players:
        data.append({
            "team_id": team_id,
            "team": team_name,
            "player": p.text.strip()
        })

    time.sleep(DELAY)
df = pd.DataFrame(data)

if df.empty:
    raise Exception("No se extrajeron jugadores. Posible cambio en la web.")

print("Jugadores encontrados:", len(data))
df.to_csv("sbbl_players.csv", index=False)
print("Dataset guardado")

from datetime import datetime

with open("last_update.txt", "w") as f:
    f.write(datetime.now().strftime("%d %b %Y %H:%M"))
